<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'page#needsRole', 'url' => '/needs-role', 'verb' => 'GET'],
		['name' => 'page#dashboard', 'url' => '/dashboard', 'verb' => 'GET'],
		['name' => 'page#todayBoard', 'url' => '/today', 'verb' => 'GET'],
		['name' => 'page#patterns', 'url' => '/patterns', 'verb' => 'GET'],
		['name' => 'page#roster', 'url' => '/roster', 'verb' => 'GET'],
		['name' => 'page#rosterPrint', 'url' => '/roster/print', 'verb' => 'GET'],
		['name' => 'page#periods', 'url' => '/periods', 'verb' => 'GET'],
		['name' => 'page#employees', 'url' => '/employees', 'verb' => 'GET'],
		['name' => 'page#locations', 'url' => '/locations', 'verb' => 'GET'],
		['name' => 'page#absences', 'url' => '/absences', 'verb' => 'GET'],
		['name' => 'page#myRoster', 'url' => '/my-roster', 'verb' => 'GET'],
		['name' => 'page#myAbsences', 'url' => '/my-absences', 'verb' => 'GET'],
		['name' => 'page#settings', 'url' => '/settings', 'verb' => 'GET'],
		// Keep the requirement literal (route files load without the app autoloader).
		// tests/Unit/Controller/SettingsPagesContractTest pins it to SettingsSectionCatalog::routeRequirement().
		['name' => 'page#settingsSection', 'url' => '/settings/{section}', 'verb' => 'GET',
			'requirements' => ['section' => 'access|duty-roles|planning|companies|conflicts|shift-templates|qualifications|planner-scope|operations|dienst-team|integration|privacy|license|support']],
		['name' => 'api#bootstrap', 'url' => '/api/bootstrap', 'verb' => 'GET'],
		['name' => 'catalogApi#timezones', 'url' => '/api/catalog/timezones', 'verb' => 'GET'],
		['name' => 'rosterApi#dashboard', 'url' => '/api/dashboard', 'verb' => 'GET'],
		['name' => 'rosterApi#roster', 'url' => '/api/roster', 'verb' => 'GET'],
		['name' => 'rosterApi#listPeriods', 'url' => '/api/periods', 'verb' => 'GET'],
		['name' => 'rosterApi#createPeriod', 'url' => '/api/periods', 'verb' => 'POST'],
		['name' => 'rosterApi#ensureCalendarMonth', 'url' => '/api/periods/ensure-calendar-month', 'verb' => 'POST'],
		['name' => 'rosterApi#transitionPeriod', 'url' => '/api/periods/{id}/transition', 'verb' => 'POST'],
		['name' => 'rosterApi#publishPeriod', 'url' => '/api/periods/{id}/publish', 'verb' => 'POST'],
		['name' => 'rosterApi#closePeriod', 'url' => '/api/periods/{id}/close', 'verb' => 'POST'],
		['name' => 'rosterApi#reopenPeriod', 'url' => '/api/periods/{id}/reopen', 'verb' => 'POST'],
		['name' => 'rosterApi#periodSnapshots', 'url' => '/api/periods/{id}/snapshots', 'verb' => 'GET'],
		['name' => 'rosterApi#verifyPeriodSnapshots', 'url' => '/api/periods/{id}/snapshots/verify', 'verb' => 'GET'],
		['name' => 'rosterApi#publishReadiness', 'url' => '/api/periods/{id}/publish-readiness', 'verb' => 'GET'],
		['name' => 'rosterApi#periodAudit', 'url' => '/api/periods/{id}/audit', 'verb' => 'GET'],
		['name' => 'rosterApi#exportRosterCsv', 'url' => '/api/admin/roster-export', 'verb' => 'GET'],
		['name' => 'rosterApi#createAssignment', 'url' => '/api/assignments', 'verb' => 'POST'],
		['name' => 'rosterApi#updateAssignment', 'url' => '/api/assignments/{id}', 'verb' => 'PUT'],
		// Same-name registrations replace each other in the route collection —
		// the postfix keeps both verbs reachable.
		['name' => 'rosterApi#updateAssignment', 'url' => '/api/assignments/{id}', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'rosterApi#cancelAssignment', 'url' => '/api/assignments/{id}/cancel', 'verb' => 'POST'],
		['name' => 'rosterApi#acknowledgeAssignment', 'url' => '/api/my/assignments/{id}/acknowledge', 'verb' => 'POST'],
		['name' => 'rosterApi#periodAcknowledgeStats', 'url' => '/api/periods/{id}/acknowledge-stats', 'verb' => 'GET'],
		['name' => 'rosterApi#copyPeriod', 'url' => '/api/periods/{id}/copy', 'verb' => 'POST'],
		['name' => 'rosterApi#listTemplates', 'url' => '/api/templates', 'verb' => 'GET'],
		['name' => 'rosterApi#createTemplate', 'url' => '/api/templates', 'verb' => 'POST'],
		['name' => 'rosterApi#updateTemplate', 'url' => '/api/templates/{id}', 'verb' => 'PUT'],
		['name' => 'rosterApi#updateTemplate', 'url' => '/api/templates/{id}', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'rosterApi#deleteTemplate', 'url' => '/api/templates/{id}', 'verb' => 'DELETE'],
		['name' => 'rosterApi#conflictPolicy', 'url' => '/api/admin/conflict-policy', 'verb' => 'GET'],
		['name' => 'rosterApi#saveConflictPolicy', 'url' => '/api/admin/conflict-policy', 'verb' => 'POST'],
		['name' => 'rosterApi#applyConflictPolicyToOpenPeriods', 'url' => '/api/admin/conflict-policy/apply-open', 'verb' => 'POST'],
		['name' => 'rosterApi#listQualifications', 'url' => '/api/qualifications', 'verb' => 'GET'],
		['name' => 'rosterApi#createQualification', 'url' => '/api/qualifications', 'verb' => 'POST'],
		['name' => 'rosterApi#updateQualification', 'url' => '/api/qualifications/{id}', 'verb' => 'PUT'],
		['name' => 'rosterApi#updateQualification', 'url' => '/api/qualifications/{id}', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'rosterApi#deactivateQualification', 'url' => '/api/qualifications/{id}/deactivate', 'verb' => 'POST'],
		['name' => 'rosterApi#listOpenShifts', 'url' => '/api/open-shifts', 'verb' => 'GET'],
		['name' => 'rosterApi#listPendingOpenShifts', 'url' => '/api/open-shifts/pending', 'verb' => 'GET'],
		['name' => 'rosterApi#createOpenShift', 'url' => '/api/open-shifts', 'verb' => 'POST'],
		['name' => 'rosterApi#claimOpenShift', 'url' => '/api/open-shifts/{id}/claim', 'verb' => 'POST'],
		['name' => 'rosterApi#approveOpenShiftClaim', 'url' => '/api/open-shifts/{id}/approve', 'verb' => 'POST'],
		['name' => 'rosterApi#rejectOpenShiftClaim', 'url' => '/api/open-shifts/{id}/reject', 'verb' => 'POST'],
		['name' => 'rosterApi#listSwapRequests', 'url' => '/api/swaps', 'verb' => 'GET'],
		['name' => 'rosterApi#createSwapRequest', 'url' => '/api/swaps', 'verb' => 'POST'],
		['name' => 'rosterApi#reviewSwapRequest', 'url' => '/api/swaps/{id}/review', 'verb' => 'POST'],
		['name' => 'selfServiceApi#acceptSwap', 'url' => '/api/swaps/{id}/accept', 'verb' => 'POST'],
		['name' => 'rosterApi#swapCandidates', 'url' => '/api/my/swap-candidates', 'verb' => 'GET'],
		['name' => 'selfServiceApi#getSettings', 'url' => '/api/self-service/settings', 'verb' => 'GET'],
		['name' => 'selfServiceApi#updateSettings', 'url' => '/api/self-service/settings', 'verb' => 'PUT'],
		['name' => 'selfServiceApi#updateSettings', 'url' => '/api/self-service/settings', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'selfServiceApi#listPatterns', 'url' => '/api/rotation-patterns', 'verb' => 'GET'],
		['name' => 'selfServiceApi#getPattern', 'url' => '/api/rotation-patterns/{id}', 'verb' => 'GET'],
		['name' => 'selfServiceApi#createPattern', 'url' => '/api/rotation-patterns', 'verb' => 'POST'],
		['name' => 'selfServiceApi#updatePattern', 'url' => '/api/rotation-patterns/{id}', 'verb' => 'PUT'],
		['name' => 'selfServiceApi#deactivatePattern', 'url' => '/api/rotation-patterns/{id}/deactivate', 'verb' => 'POST'],
		['name' => 'selfServiceApi#assignPattern', 'url' => '/api/rotation-patterns/{id}/assign', 'verb' => 'POST'],
		['name' => 'selfServiceApi#listEmployeeRotationAssignments', 'url' => '/api/employees/{id}/rotation-assignments', 'verb' => 'GET'],
		['name' => 'selfServiceApi#endRotationAssignment', 'url' => '/api/rotation-assignments/{id}/end', 'verb' => 'POST'],
		['name' => 'selfServiceApi#suggestPreview', 'url' => '/api/periods/{id}/suggest-preview', 'verb' => 'POST'],
		['name' => 'selfServiceApi#suggestConfirm', 'url' => '/api/periods/{id}/suggest-confirm', 'verb' => 'POST'],
		['name' => 'selfServiceApi#teamWeek', 'url' => '/api/team-week', 'verb' => 'GET'],
		['name' => 'selfServiceApi#teamLocations', 'url' => '/api/team-locations', 'verb' => 'GET'],
		['name' => 'selfServiceApi#todayBoard', 'url' => '/api/today-board', 'verb' => 'GET'],
		['name' => 'selfServiceApi#myPreferences', 'url' => '/api/my/preferences', 'verb' => 'GET'],
		['name' => 'selfServiceApi#saveMyPreference', 'url' => '/api/my/preferences', 'verb' => 'POST'],
		['name' => 'selfServiceApi#deleteMyPreference', 'url' => '/api/my/preferences/{id}', 'verb' => 'DELETE'],
		['name' => 'selfServiceApi#myBlackouts', 'url' => '/api/my/blackouts', 'verb' => 'GET'],
		['name' => 'selfServiceApi#createMyBlackout', 'url' => '/api/my/blackouts', 'verb' => 'POST'],
		['name' => 'selfServiceApi#deleteMyBlackout', 'url' => '/api/my/blackouts/{id}', 'verb' => 'DELETE'],
		['name' => 'selfServiceApi#employeePreferences', 'url' => '/api/employees/{id}/preferences', 'verb' => 'GET'],
		['name' => 'selfServiceApi#employeeBlackouts', 'url' => '/api/employees/{id}/blackouts', 'verb' => 'GET'],
		['name' => 'selfServiceApi#rosterSignals', 'url' => '/api/roster/signals', 'verb' => 'GET'],
		['name' => 'selfServiceApi#blackoutOverride', 'url' => '/api/assignments/{id}/blackout-override', 'verb' => 'POST'],
		['name' => 'selfServiceApi#sollDiagnostics', 'url' => '/api/admin/soll-diagnostics', 'verb' => 'GET'],
		['name' => 'license#show', 'url' => '/api/license', 'verb' => 'GET'],
		['name' => 'license#apply', 'url' => '/api/license', 'verb' => 'POST'],
		['name' => 'license#remove', 'url' => '/api/license', 'verb' => 'DELETE'],
		['name' => 'license#seats', 'url' => '/api/license/seats', 'verb' => 'GET'],
		['name' => 'license#assignSeat', 'url' => '/api/license/seats', 'verb' => 'POST'],
		['name' => 'license#removeSeat', 'url' => '/api/license/seats/{uid}', 'verb' => 'DELETE'],
		['name' => 'license#searchUsers', 'url' => '/api/license/search/users', 'verb' => 'GET'],
		['name' => 'mobile#bootstrap', 'url' => '/api/mobile/bootstrap', 'verb' => 'GET'],
		['name' => 'mobile#myRoster', 'url' => '/api/mobile/my/roster', 'verb' => 'GET'],
		['name' => 'mobile#acknowledgeAssignment', 'url' => '/api/mobile/my/assignments/{id}/acknowledge', 'verb' => 'POST'],
		['name' => 'mobile#myAbsences', 'url' => '/api/mobile/my/absences', 'verb' => 'GET'],
		['name' => 'mobile#createMyAbsence', 'url' => '/api/mobile/my/absences', 'verb' => 'POST'],
		['name' => 'mobile#listOpenShifts', 'url' => '/api/mobile/open-shifts', 'verb' => 'GET'],
		['name' => 'mobile#claimOpenShift', 'url' => '/api/mobile/open-shifts/{id}/claim', 'verb' => 'POST'],
		['name' => 'mobile#createSwapRequest', 'url' => '/api/mobile/swaps', 'verb' => 'POST'],
		['name' => 'mobile#acceptSwap', 'url' => '/api/mobile/swaps/{id}/accept', 'verb' => 'POST'],
		['name' => 'mobile#swapCandidates', 'url' => '/api/mobile/my/swap-candidates', 'verb' => 'GET'],
		['name' => 'mobile#teamWeek', 'url' => '/api/mobile/team-week', 'verb' => 'GET'],
		['name' => 'mobile#myPreferences', 'url' => '/api/mobile/my/preferences', 'verb' => 'GET'],
		['name' => 'mobile#saveMyPreference', 'url' => '/api/mobile/my/preferences', 'verb' => 'POST'],
		['name' => 'mobile#deleteMyPreference', 'url' => '/api/mobile/my/preferences/{id}', 'verb' => 'DELETE'],
		['name' => 'mobile#myBlackouts', 'url' => '/api/mobile/my/blackouts', 'verb' => 'GET'],
		['name' => 'mobile#createMyBlackout', 'url' => '/api/mobile/my/blackouts', 'verb' => 'POST'],
		['name' => 'mobile#deleteMyBlackout', 'url' => '/api/mobile/my/blackouts/{id}', 'verb' => 'DELETE'],
		['name' => 'mobile#icalTokenMeta', 'url' => '/api/mobile/me/ical-token', 'verb' => 'GET'],
		['name' => 'mobile#createIcalToken', 'url' => '/api/mobile/me/ical-token', 'verb' => 'POST'],
		['name' => 'mobile#rotateIcalToken', 'url' => '/api/mobile/me/ical-token/rotate', 'verb' => 'POST'],

		['name' => 'rosterApi#acknowledgeConflict', 'url' => '/api/conflicts/{id}/acknowledge', 'verb' => 'POST'],
		['name' => 'rosterApi#absences', 'url' => '/api/absences', 'verb' => 'GET'],
		['name' => 'rosterApi#createAbsence', 'url' => '/api/absences', 'verb' => 'POST'],
		['name' => 'rosterApi#transitionAbsence', 'url' => '/api/absences/{id}/transition', 'verb' => 'POST'],
		['name' => 'rosterApi#employees', 'url' => '/api/employees', 'verb' => 'GET'],
		['name' => 'rosterApi#createEmployee', 'url' => '/api/employees', 'verb' => 'POST'],
		['name' => 'rosterApi#updateEmployee', 'url' => '/api/employees/{id}', 'verb' => 'PUT'],
		['name' => 'rosterApi#updateEmployee', 'url' => '/api/employees/{id}', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'rosterApi#directoryUsers', 'url' => '/api/admin/users', 'verb' => 'GET'],
		['name' => 'rosterApi#directoryGroups', 'url' => '/api/admin/groups', 'verb' => 'GET'],
		['name' => 'rosterApi#appPolicy', 'url' => '/api/admin/policy', 'verb' => 'GET'],
		['name' => 'rosterApi#saveAppPolicy', 'url' => '/api/admin/policy', 'verb' => 'POST'],
		['name' => 'rosterApi#listDutyRoles', 'url' => '/api/admin/duty-roles', 'verb' => 'GET'],
		['name' => 'rosterApi#setDutyRole', 'url' => '/api/admin/duty-roles', 'verb' => 'POST'],
		['name' => 'rosterApi#removeDutyRole', 'url' => '/api/admin/duty-roles/{userId}', 'verb' => 'DELETE'],
		['name' => 'rosterApi#planningDefaults', 'url' => '/api/admin/planning-defaults', 'verb' => 'GET'],
		['name' => 'rosterApi#savePlanningDefaults', 'url' => '/api/admin/planning-defaults', 'verb' => 'POST'],
		['name' => 'rosterApi#opsFlags', 'url' => '/api/admin/ops-flags', 'verb' => 'GET'],
		['name' => 'rosterApi#saveOpsFlags', 'url' => '/api/admin/ops-flags', 'verb' => 'POST'],
		['name' => 'rosterApi#pruneSnapshots', 'url' => '/api/admin/snapshots/prune', 'verb' => 'POST'],
		['name' => 'rosterApi#exportRosterMinutesCsv', 'url' => '/api/admin/periods/{periodId}/roster-minutes.csv', 'verb' => 'GET'],
		['name' => 'rosterApi#listCompanies', 'url' => '/api/admin/companies', 'verb' => 'GET'],
		['name' => 'rosterApi#createCompany', 'url' => '/api/admin/companies', 'verb' => 'POST'],
		['name' => 'rosterApi#listCompanyMembers', 'url' => '/api/admin/companies/{id}/members', 'verb' => 'GET'],
		['name' => 'rosterApi#addCompanyMember', 'url' => '/api/admin/companies/{id}/members', 'verb' => 'POST'],
		['name' => 'rosterApi#removeCompanyMember', 'url' => '/api/admin/companies/{id}/members/{userId}', 'verb' => 'DELETE'],
		['name' => 'rosterApi#onDutyToday', 'url' => '/api/integrations/on-duty', 'verb' => 'GET'],
		['name' => 'rosterApi#attachEmployeeQualification', 'url' => '/api/employees/{id}/qualifications', 'verb' => 'POST'],
		['name' => 'rosterApi#detachEmployeeQualification', 'url' => '/api/employees/{id}/qualifications/{qualificationId}', 'verb' => 'DELETE'],
		['name' => 'rosterApi#detachEmployeeQualification', 'url' => '/api/employees/{id}/qualifications/{qualificationId}/detach', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'rosterApi#requireLocationQualification', 'url' => '/api/locations/{id}/qualifications', 'verb' => 'POST'],
		['name' => 'rosterApi#plannerLocationScope', 'url' => '/api/admin/planner-scope/{userId}', 'verb' => 'GET'],
		['name' => 'rosterApi#setPlannerLocationScope', 'url' => '/api/admin/planner-scope/{userId}', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationStatus', 'url' => '/api/admin/integration', 'verb' => 'GET'],
		['name' => 'rosterApi#integrationIntent', 'url' => '/api/admin/integration/intent', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationSyncNow', 'url' => '/api/admin/integration/sync', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationSettings', 'url' => '/api/admin/integration/settings', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationPurgeLegacyAbsences', 'url' => '/api/admin/integration/purge-legacy-absences', 'verb' => 'POST'],
		['name' => 'rosterApi#locations', 'url' => '/api/locations', 'verb' => 'GET'],
		['name' => 'rosterApi#createLocation', 'url' => '/api/locations', 'verb' => 'POST'],
		['name' => 'rosterApi#updateLocation', 'url' => '/api/locations/{id}', 'verb' => 'PUT'],
		['name' => 'rosterApi#updateLocation', 'url' => '/api/locations/{id}', 'verb' => 'POST', 'postfix' => 'post'],
		['name' => 'rosterApi#myRoster', 'url' => '/api/my/roster', 'verb' => 'GET'],
		['name' => 'rosterApi#myAbsences', 'url' => '/api/my/absences', 'verb' => 'GET'],
		['name' => 'rosterApi#createMyAbsence', 'url' => '/api/my/absences', 'verb' => 'POST'],
		['name' => 'rosterApi#myIcalToken', 'url' => '/api/me/ical-token', 'verb' => 'GET'],
		['name' => 'rosterApi#rotateMyIcalToken', 'url' => '/api/me/ical-token/rotate', 'verb' => 'POST'],
		['name' => 'rosterApi#publicIcal', 'url' => '/api/ical/{employeeId}', 'verb' => 'GET'],
	],
];
