<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'page#dashboard', 'url' => '/dashboard', 'verb' => 'GET'],
		['name' => 'page#roster', 'url' => '/roster', 'verb' => 'GET'],
		['name' => 'page#rosterPrint', 'url' => '/roster/print', 'verb' => 'GET'],
		['name' => 'page#periods', 'url' => '/periods', 'verb' => 'GET'],
		['name' => 'page#employees', 'url' => '/employees', 'verb' => 'GET'],
		['name' => 'page#locations', 'url' => '/locations', 'verb' => 'GET'],
		['name' => 'page#absences', 'url' => '/absences', 'verb' => 'GET'],
		['name' => 'page#myRoster', 'url' => '/my-roster', 'verb' => 'GET'],
		['name' => 'page#myAbsences', 'url' => '/my-absences', 'verb' => 'GET'],
		['name' => 'page#settings', 'url' => '/settings', 'verb' => 'GET'],
		['name' => 'api#bootstrap', 'url' => '/api/bootstrap', 'verb' => 'GET'],
		['name' => 'catalogApi#timezones', 'url' => '/api/catalog/timezones', 'verb' => 'GET'],
		['name' => 'rosterApi#dashboard', 'url' => '/api/dashboard', 'verb' => 'GET'],
		['name' => 'rosterApi#roster', 'url' => '/api/roster', 'verb' => 'GET'],
		['name' => 'rosterApi#createPeriod', 'url' => '/api/periods', 'verb' => 'POST'],
		['name' => 'rosterApi#transitionPeriod', 'url' => '/api/periods/{id}/transition', 'verb' => 'POST'],
		['name' => 'rosterApi#publishPeriod', 'url' => '/api/periods/{id}/publish', 'verb' => 'POST'],
		['name' => 'rosterApi#closePeriod', 'url' => '/api/periods/{id}/close', 'verb' => 'POST'],
		['name' => 'rosterApi#reopenPeriod', 'url' => '/api/periods/{id}/reopen', 'verb' => 'POST'],
		['name' => 'rosterApi#periodSnapshots', 'url' => '/api/periods/{id}/snapshots', 'verb' => 'GET'],
		['name' => 'rosterApi#verifyPeriodSnapshots', 'url' => '/api/periods/{id}/snapshots/verify', 'verb' => 'GET'],
		['name' => 'rosterApi#publishReadiness', 'url' => '/api/periods/{id}/publish-readiness', 'verb' => 'GET'],
		['name' => 'rosterApi#periodAudit', 'url' => '/api/periods/{id}/audit', 'verb' => 'GET'],
		['name' => 'rosterApi#exportRosterCsv', 'url' => '/api/admin/roster-export', 'verb' => 'GET'],
		['name' => 'rosterApi#createAssignment', 'url' => '/api/assignments', 'verb' => 'POST'],
		['name' => 'rosterApi#acknowledgeConflict', 'url' => '/api/conflicts/{id}/acknowledge', 'verb' => 'POST'],
		['name' => 'rosterApi#absences', 'url' => '/api/absences', 'verb' => 'GET'],
		['name' => 'rosterApi#createAbsence', 'url' => '/api/absences', 'verb' => 'POST'],
		['name' => 'rosterApi#transitionAbsence', 'url' => '/api/absences/{id}/transition', 'verb' => 'POST'],
		['name' => 'rosterApi#employees', 'url' => '/api/employees', 'verb' => 'GET'],
		['name' => 'rosterApi#createEmployee', 'url' => '/api/employees', 'verb' => 'POST'],
		['name' => 'rosterApi#updateEmployee', 'url' => '/api/employees/{id}', 'verb' => 'PUT'],
		['name' => 'rosterApi#updateEmployee', 'url' => '/api/employees/{id}', 'verb' => 'POST'],
		['name' => 'rosterApi#directoryUsers', 'url' => '/api/admin/users', 'verb' => 'GET'],
		['name' => 'rosterApi#directoryGroups', 'url' => '/api/admin/groups', 'verb' => 'GET'],
		['name' => 'rosterApi#appPolicy', 'url' => '/api/admin/policy', 'verb' => 'GET'],
		['name' => 'rosterApi#saveAppPolicy', 'url' => '/api/admin/policy', 'verb' => 'POST'],
		['name' => 'rosterApi#planningDefaults', 'url' => '/api/admin/planning-defaults', 'verb' => 'GET'],
		['name' => 'rosterApi#savePlanningDefaults', 'url' => '/api/admin/planning-defaults', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationStatus', 'url' => '/api/admin/integration', 'verb' => 'GET'],
		['name' => 'rosterApi#integrationIntent', 'url' => '/api/admin/integration/intent', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationSyncNow', 'url' => '/api/admin/integration/sync', 'verb' => 'POST'],
		['name' => 'rosterApi#integrationPurgeLegacyAbsences', 'url' => '/api/admin/integration/purge-legacy-absences', 'verb' => 'POST'],
		['name' => 'rosterApi#locations', 'url' => '/api/locations', 'verb' => 'GET'],
		['name' => 'rosterApi#createLocation', 'url' => '/api/locations', 'verb' => 'POST'],
		['name' => 'rosterApi#updateLocation', 'url' => '/api/locations/{id}', 'verb' => 'PUT'],
		['name' => 'rosterApi#updateLocation', 'url' => '/api/locations/{id}', 'verb' => 'POST'],
		['name' => 'rosterApi#myRoster', 'url' => '/api/my/roster', 'verb' => 'GET'],
		['name' => 'rosterApi#myAbsences', 'url' => '/api/my/absences', 'verb' => 'GET'],
		['name' => 'rosterApi#createMyAbsence', 'url' => '/api/my/absences', 'verb' => 'POST'],
		['name' => 'rosterApi#myIcalToken', 'url' => '/api/me/ical-token', 'verb' => 'GET'],
		['name' => 'rosterApi#rotateMyIcalToken', 'url' => '/api/me/ical-token/rotate', 'verb' => 'POST'],
		['name' => 'rosterApi#publicIcal', 'url' => '/api/ical/{employeeId}', 'verb' => 'GET'],
	],
];
