#!/usr/bin/env python3
"""Generate formal_scandinavian_data.json — hand-written da/sv/nb B2B translations."""
from __future__ import annotations

import json
from pathlib import Path

T: dict[str, dict[str, str]] = {}


def a(key: str, da: str, sv: str, nb: str) -> None:
    T[key] = {"da": da, "sv": sv, "nb": nb}


# Support strings (4)
a(
    "%s stays free (AGPL) on your Nextcloud. Bug reports and ideas on GitHub stay welcome — that is free open-source care. If your organisation needs bookable help on an invoice — or official mobile licenses — choose an option below:",
    "%s forbliver gratis (AGPL) på Nextcloud. Fejlrapporter og idéer på GitHub er velkomne — det er gratis open source-pleje. Hvis organisationen har brug for bookbar hjælp på en faktura — eller officielle mobillicenser — skal der vælges en mulighed nedenfor:",
    "%s förblir gratis (AGPL) på Nextcloud. Felrapporter och idéer på GitHub är välkomna — det är gratis open source-omsorg. Om organisationen behöver bokningsbar hjälp på faktura — eller officiella mobillicenser — välj ett alternativ nedan:",
    "%s forblir gratis (AGPL) på Nextcloud. Feilrapporter og ideer på GitHub er velkomne — det er gratis open source-støtte. Hvis organisasjonen trenger bestillbar hjelp på faktura — eller offisielle mobil-lisenser — velg et alternativ nedenfor:",
)
a(
    "%s stays free (AGPL) on your Nextcloud. Bug reports and ideas on GitHub stay welcome — that is free open-source care. If your organisation needs bookable help on an invoice, choose an option below:",
    "%s forbliver gratis (AGPL) på Nextcloud. Fejlrapporter og idéer på GitHub er velkomne — det er gratis open source-pleje. Hvis organisationen har brug for bookbar hjælp på en faktura, skal der vælges en mulighed nedenfor:",
    "%s förblir gratis (AGPL) på Nextcloud. Felrapporter och idéer på GitHub är välkomna — det är gratis open source-omsorg. Om organisationen behöver bokningsbar hjälp på faktura, välj ett alternativ nedan:",
    "%s forblir gratis (AGPL) på Nextcloud. Feilrapporter og ideer på GitHub er velkomne — det er gratis open source-støtte. Hvis organisasjonen trenger bestillbar hjelp på faktura, velg et alternativ nedenfor:",
)
a(
    "%s stays free (AGPL) on your Nextcloud. GitHub issues for bugs and ideas remain welcome. For bookable help on an invoice — setup, hour packs, commissioned work — or the official mobile app:",
    "%s forbliver gratis (AGPL) på Nextcloud. GitHub-issues for fejl og idéer er velkomne. For bookbar hjælp på faktura — opsætning, timepakker, bestillingsarbejde — eller den officielle mobilapp:",
    "%s förblir gratis (AGPL) på Nextcloud. GitHub-ärenden för buggar och idéer är välkomna. För bokningsbar hjälp på faktura — installation, timpaket, beställningsarbete — eller den officiella mobilappen:",
    "%s forblir gratis (AGPL) på Nextcloud. GitHub-saker for feil og ideer er velkomne. For bestillbar hjelp på faktura — oppsett, timepakker, bestillingsarbeid — eller den offisielle mobilappen:",
)
a(
    "%s stays free (AGPL) on your Nextcloud. GitHub issues for bugs and ideas remain welcome. For bookable help on an invoice — setup, hour packs, or commissioned work:",
    "%s forbliver gratis (AGPL) på Nextcloud. GitHub-issues for fejl og idéer er velkomne. For bookbar hjælp på faktura — opsætning, timepakker eller bestillingsarbejde:",
    "%s förblir gratis (AGPL) på Nextcloud. GitHub-ärenden för buggar och idéer är välkomna. För bokningsbar hjälp på faktura — installation, timpaket eller beställningsarbete:",
    "%s forblir gratis (AGPL) på Nextcloud. GitHub-saker for feil og ideer er velkomne. For bestillbar hjelp på faktura — oppsett, timepakker eller bestillingsarbeid:",
)

# Planning workflow
a("1. Choose the period to plan in", "1. Vælg planlægningsperioden", "1. Välj planeringsperioden", "1. Velg planleggingsperioden")
a("2. Add allowlist entries before turning restriction on", "2. Tilføj tilladelsesposter, før begrænsningen aktiveres", "2. Lägg till godkännandelisteposter innan begränsningen aktiveras", "2. Legg til godkjenningslisteoppføringer før begrensningen aktiveres")
a("A date range you plan in: open → published → closed.", "Et datointerval, der planlægges i: åben → offentliggjort → lukket.", "Ett datumintervall att planera i: öppen → publicerad → stängd.", "Et datointervall som planlegges i: åpen → publisert → lukket.")
a(
    'A link is active. The full address is hidden here for safety. Replace the link if you need to copy it again.',
    "Et link er aktivt. Den fulde adresse er skjult her af sikkerhedshensyn. Erstat linket, hvis adressen skal kopieres igen.",
    "En länk är aktiv. Den fullständiga adressen är dold här av säkerhetsskäl. Byt länk om adressen behöver kopieras igen.",
    "En lenke er aktiv. Hele adressen er skjult her av sikkerhetsgrunner. Erstatt lenken hvis adressen må kopieres igjen.",
)
a(
    'A period is a date range (e.g. one month) in which assignments are created. Open the Periods page, pick a start and end date, and the period stays "Open" so you can plan inside it.',
    "En periode er et datointerval (f.eks. en måned), hvor tildelinger oprettes. Åbn siden Perioder, vælg start- og slutdato — perioden forbliver «Åben», så der kan planlægges i den.",
    "En period är ett datumintervall (t.ex. en månad) där uppdrag skapas. Öppna sidan Perioder, välj start- och slutdatum — perioden förblir «Öppen» så att planering kan ske i den.",
    "En periode er et datointervall (f.eks. én måned) der oppdrag opprettes. Åpne siden Perioder, velg start- og sluttdato — perioden forblir «Åpen», slik at det kan planlegges i den.",
)
a(
    "A period is a window (e.g. a month) in which you plan duties. Pick start and end dates below — overlapping ranges are blocked automatically.",
    "En periode er et vindue (f.eks. en måned) til planlægning af vagter. Vælg start- og slutdato nedenfor — overlappende intervaller blokeres automatisk.",
    "En period är ett fönster (t.ex. en månad) för planering av pass. Välj start- och slutdatum nedan — överlappande intervall blockeras automatiskt.",
    "En periode er et vindu (f.eks. én måned) for planlegging av vakter. Velg start- og sluttdato nedenfor — overlappende intervaller blokkeres automatisk.",
)
a(
    "A planning rule needs your confirmation before this shift can be saved.",
    "En planlægningsregel kræver bekræftelse, før denne vagt kan gemmes.",
    "En planeringsregel kräver bekräftelse innan detta pass kan sparas.",
    "En planleggingsregel krever bekreftelse før dette skiftet kan lagres.",
)
a(
    "A snapshot of the current planning workload. Numbers update each time you reload the page.",
    "Et øjebliksbillede af den aktuelle planlægningsbyrde. Tallene opdateres ved hver sidegenindlæsning.",
    "En ögonblicksbild av den aktuella planeringsbelastningen. Siffrorna uppdateras vid varje siduppdatering.",
    "Et øyeblikksbilde av gjeldende planleggingsarbeid. Tall oppdateres ved hver sideoppdatering.",
)
a(
    "A soft conflict you may keep after writing a short reason (≥ 10 characters).",
    "En blød konflikt, der må beholdes efter en kort begrundelse (≥ 10 tegn).",
    "En mjuk konflikt som får behållas efter en kort motivering (≥ 10 tecken).",
    "En myk konflikt som kan beholdes etter en kort begrunnelse (≥ 10 tegn).",
)
a(
    "A yearly pack of hours you can book with us, plus priority email replies for your organisation. This is invoiceable service — not a donation.",
    "En årlig pakke med timer, der kan bestilles hos os, plus prioriterede e-mailsvar til organisationen. Dette er fakturerbar service — ikke en donation.",
    "Ett årspaket med timmar som kan bokas hos oss, plus prioriterade e-postsvar för organisationen. Detta är fakturerbar tjänst — inte en donation.",
    "En årlig pakke med timer som kan bestilles hos oss, pluss prioriterte e-postsvar for organisasjonen. Dette er fakturerbar tjeneste — ikke en donasjon.",
)

a(
    "Absences for linked people are kept in ArbeitszeitCheck. This page lists them so you can spot roster clashes. You can add absences here only for people who are not linked.",
    "Fravær for linkede personer opbevares i ArbeitszeitCheck. Denne side viser dem, så vagtplan-konflikter kan opdages. Fravær kan kun tilføjes her for personer, der ikke er linket.",
    "Frånvaro för länkade personer sparas i ArbeitszeitCheck. Den här sidan listar dem så att schema-konflikter kan upptäckas. Frånvaro kan bara läggas till här för personer som inte är länkade.",
    "Fravær for tilknyttede personer oppbevares i ArbeitszeitCheck. Denne siden viser dem slik at vaktplan-konflikter kan oppdages. Fravær kan bare legges til her for personer som ikke er tilknyttet.",
)
a("Add at least one active employee before planning shifts.", "Tilføj mindst én aktiv medarbejder, før vagter planlægges.", "Lägg till minst en aktiv anställd innan pass planeras.", "Legg til minst én aktiv ansatt før vakter planlegges.")
a("Add at least one active location before planning shifts.", "Tilføj mindst én aktiv lokation, før vagter planlægges.", "Lägg till minst en aktiv plats innan pass planeras.", "Legg til minst ett aktivt sted før vakter planlegges.")
a("Add shifts to your personal calendar", "Tilføj vagter til kalenderen", "Lägg till pass i kalendern", "Legg til vakter i kalenderen")
a(
    "Add the people who work shifts (Employees) and the places where shifts happen (Locations). You only do this once per organisation.",
    "Tilføj personer, der arbejder vagter (Medarbejdere), og steder, hvor vagter foregår (Lokationer). Det gøres kun én gang pr. organisation.",
    "Lägg till personer som arbetar pass (Anställda) och platser där pass sker (Platser). Detta görs bara en gång per organisation.",
    "Legg til personer som jobber vakter (Ansatte) og steder der vakter skjer (Steder). Dette gjøres bare én gang per organisasjon.",
)
a(
    "Adding users or groups here only lets them open DutyCheck. Planners need a duty role in the section below. Staff need their Nextcloud account linked to an employee record on the Employees page.",
    "Tilføjede brugere eller grupper kan her kun åbne DutyCheck. Planlæggere skal have en vagtrolle i afsnittet nedenfor. Medarbejdere skal have Nextcloud-kontoen linket til en medarbejderpost på siden Medarbejdere.",
    "Tillagda användare eller grupper kan här bara öppna DutyCheck. Planerare behöver en passroll i avsnittet nedan. Personal behöver sitt Nextcloud-konto kopplat till en anställdpost på sidan Anställda.",
    "Tillagte brukere eller grupper kan her bare åpne DutyCheck. Planleggere trenger en vaktrolle i avsnittet nedenfor. Ansatte trenger Nextcloud-kontoen koblet til en ansattpost på siden Ansatte.",
)
a(
    "After approval, open the Roster — overlapping shifts appear as “Must fix” and must be changed or removed before you publish.",
    "Efter godkendelse skal vagtplanen åbnes — overlappende vagter vises som «Skal rettes» og skal ændres eller fjernes, før der offentliggøres.",
    "Efter godkännande ska schemat öppnas — överlappande pass visas som «Måste åtgärdas» och måste ändras eller tas bort innan publicering.",
    "Etter godkjenning må vaktplanen åpnes — overlappende vakter vises som «Må rettes» og må endres eller fjernes før publisering.",
)
a(
    "Always add at least one user or group to the allowlist before enabling the restriction toggle. Otherwise the app locks itself — including you, until a system admin re-opens it.",
    "Tilføj altid mindst én bruger eller gruppe til tilladelseslisten, før begrænsningen aktiveres. Ellers låser appen sig selv — også for den aktuelle bruger — indtil en systemadministrator genåbner den.",
    "Lägg alltid till minst en användare eller grupp på godkännandelistan innan begränsningen aktiveras. Annars låser appen sig själv — även för den aktuella användaren — tills en systemadministratör öppnar den igen.",
    "Legg alltid til minst én bruker eller gruppe på godkjenningslisten før begrensningen aktiveres. Ellers låser appen seg selv — også for den aktuelle brukeren — til en systemadministrator åpner den igjen.",
)
a(
    "Annual hour packs — Small, Standard, or Premium — with priority email for your organisation. This is invoiceable service — not a donation. See packages on our support page.",
    "Årlige timepakker — Small, Standard eller Premium — med prioriteret e-mail til organisationen. Fakturerbar service — ikke en donation. Se pakker på supportsiden.",
    "Årliga timpaket — Small, Standard eller Premium — med prioriterad e-post för organisationen. Fakturerbar tjänst — inte en donation. Se paket på supportsidan.",
    "Årlige timepakker — Small, Standard eller Premium — med prioritert e-post for organisasjonen. Fakturerbar tjeneste — ikke en donasjon. Se pakker på supportsiden.",
)
a(
    "Anyone with the link can see your published shifts. If someone else might have seen it, use “Replace calendar link” and paste the new address into your calendar app.",
    "Alle med linket kan se offentliggjorte vagter. Hvis andre kan have set det, brug «Erstat kalenderlink» og indsæt den nye adresse i kalenderappen.",
    "Alla med länken kan se publicerade pass. Om någon annan kan ha sett den, använd «Byt kalenderlänk» och klistra in den nya adressen i kalenderappen.",
    "Alle med lenken kan se publiserte vakter. Hvis andre kan ha sett den, bruk «Erstatt kalenderlenke» og lim inn den nye adressen i kalenderappen.",
)
a(
    "App administrators can change this policy and re-open closed periods. Only delegate to people you trust to handle the audit log.",
    "App-administratorer kan ændre denne politik og genåbne lukkede perioder. Deleger revisionsloggen kun til betroede personer.",
    "Appadministratörer kan ändra denna policy och öppna stängda perioder igen. Delegera granskningsloggen endast till betrodda personer.",
    "Appadministratorer kan endre denne policyen og åpne lukkede perioder på nytt. Deleger revisjonsloggen bare til betrodde personer.",
)
a("Are you sure?", "Er handlingen korrekt?", "Är åtgärden korrekt?", "Er handlingen korrekt?")
a(
    "Automatic checks for the same period as the assignment list. “Must fix” blocks publishing until resolved. “Confirm to continue” lets you proceed after you confirm with a short reason.",
    "Automatiske kontroller for samme periode som tildelingslisten. «Skal rettes» blokerer offentliggørelse, indtil det er løst. «Bekræft for at fortsætte» tillader fortsættelse efter kort begrundelse.",
    "Automatiska kontroller för samma period som uppdragslistan. «Måste åtgärdas» blockerar publicering tills det är löst. «Bekräfta för att fortsätta» tillåter fortsättning efter kort motivering.",
    "Automatiske kontroller for samme periode som oppdragslisten. «Må rettes» blokkerer publisering til det er løst. «Bekreft for å fortsette» tillater fortsettelse etter kort begrunnelse.",
)
a("Briefly explain why you are allowing this (minimum 10 characters)", "Forklar kort, hvorfor dette tillades (mindst 10 tegn)", "Förklara kort varför detta tillåts (minst 10 tecken)", "Forklar kort hvorfor dette tillates (minst 10 tegn)")
a("Briefly explain why you are approving this claim anyway (at least 10 characters).", "Forklar kort, hvorfor denne anmodning alligevel godkendes (mindst 10 tegn).", "Förklara kort varför denna begäran ändå godkänns (minst 10 tecken).", "Forklar kort hvorfor denne forespørselen likevel godkjennes (minst 10 tegn).")
a("Briefly explain why you are approving this claim anyway (at least 10 characters).\n\n{details}", "Forklar kort, hvorfor denne anmodning alligevel godkendes (mindst 10 tegn).\n\n{details}", "Förklara kort varför denna begäran ändå godkänns (minst 10 tecken).\n\n{details}", "Forklar kort hvorfor denne forespørselen likevel godkjennes (minst 10 tegn).\n\n{details}")
a("Briefly explain why you are scheduling anyway (at least 10 characters).", "Forklar kort, hvorfor planlægning alligevel fortsætter (mindst 10 tegn).", "Förklara kort varför schemaläggning ändå fortsätter (minst 10 tecken).", "Forklar kort hvorfor planlegging likevel fortsetter (minst 10 tegn).")
a("Briefly explain why you are scheduling anyway (at least 10 characters).\n\n{details}", "Forklar kort, hvorfor planlægning alligevel fortsætter (mindst 10 tegn).\n\n{details}", "Förklara kort varför schemaläggning ändå fortsätter (minst 10 tecken).\n\n{details}", "Forklar kort hvorfor planlegging likevel fortsetter (minst 10 tegn).\n\n{details}")
a("Briefly explain why you are scheduling anyway (at least 10 characters).\\n\\n{details}", "Forklar kort, hvorfor planlægning alligevel fortsætter (mindst 10 tegn).\\n\\n{details}", "Förklara kort varför schemaläggning ändå fortsätter (minst 10 tecken).\\n\\n{details}", "Forklar kort hvorfor planlegging likevel fortsetter (minst 10 tegn).\\n\\n{details}")
a("Browse your published shifts by date range and keep a private calendar subscription in sync.", "Gennemse offentliggjorte vagter efter datointerval, og hold et privat kalenderabonnement synkroniseret.", "Granska publicerade pass efter datumintervall och håll en privat kalenderprenumeration synkad.", "Se gjennom publiserte vakter etter datointervall, og hold et privat kalenderabonnement synkronisert.")
a("Calendar link is unavailable until your account is linked to an employee.", "Kalenderlink er utilgængeligt, indtil kontoen er linket til en medarbejder.", "Kalenderlänk är otillgänglig tills kontot är kopplat till en anställd.", "Kalenderlenke er utilgjengelig til kontoen er koblet til en ansatt.")
a("Cancel this shift? It will be removed from the open period and staff will not see it after publish.", "Annullere denne vagt? Den fjernes fra den åbne periode og er ikke synlig for medarbejdere efter offentliggørelse.", "Avbryta detta pass? Det tas bort från den öppna perioden och syns inte för personal efter publicering.", "Avbryte dette skiftet? Det fjernes fra den åpne perioden og vises ikke for ansatte etter publisering.")
a("Check your existing requests first, then send a new one. Your planner reviews every request.", "Gennemse eksisterende anmodninger først, og send derefter en ny. Planlæggeren gennemgår hver anmodning.", "Granska befintliga begäranden först och skicka sedan en ny. Planeraren granskar varje begäran.", "Se gjennom eksisterende forespørsler først, og send deretter en ny. Planleggeren vurderer hver forespørsel.")
a("Choose a period in the selector above before exporting or printing.", "Vælg en periode i vælgeren ovenfor, før der eksporteres eller udskrives.", "Välj en period i väljaren ovan innan export eller utskrift.", "Velg en periode i velgeren ovenfor før eksport eller utskrift.")
a("Claim sent — a planner must approve before it is on your roster.", "Anmodning sendt — en planlægger skal godkende, før vagten vises i planen.", "Begäran skickad — en planerare måste godkänna innan passet visas i schemat.", "Forespørsel sendt — en planlegger må godkjenne før vakten vises i planen.")
a("Closing a location? Deactivate it instead of deleting. New assignments stop appearing for that location, but past rosters remain intact.", "Lukkes en lokation? Deaktiver i stedet for at slette. Nye tildelinger vises ikke længere for lokationen, men tidligere vagtplaner bevares.", "Stängs en plats? Inaktivera i stället för att radera. Nya uppdrag visas inte längre för platsen, men tidigare scheman bevaras.", "Skal et sted lukkes? Deaktiver i stedet for å slette. Nye tildelinger vises ikke lenger for stedet, men tidligere vaktplaner bevares.")
a("Complete setup before adding assignments. See the checklist in this dialog.", "Fuldfør opsætningen, før tildelinger tilføjes. Se tjeklisten i denne dialog.", "Slutför konfigurationen innan uppdrag läggs till. Se checklistan i denna dialog.", "Fullfør oppsettet før tildelinger legges til. Se sjekklisten i denne dialogen.")
a("Confirm you have seen this shift", "Bekræft, at denne vagt er set", "Bekräfta att detta pass har setts", "Bekreft at dette skiftet er sett")
a("Could not load your absences. Reload the page or contact an administrator if this keeps happening.", "Fravær kunne ikke indlæses. Genindlæs siden, eller kontakt en administrator, hvis problemet fortsætter.", "Frånvaro kunde inte laddas. Ladda om sidan eller kontakta en administratör om problemet kvarstår.", "Fravær kunne ikke lastes. Last siden på nytt, eller kontakt en administrator hvis problemet fortsetter.")
a("Could not load your roster. Reload the page or contact an administrator if this keeps happening.", "Vagtplanen kunne ikke indlæses. Genindlæs siden, eller kontakt en administrator, hvis problemet fortsætter.", "Schemat kunde inte laddas. Ladda om sidan eller kontakta en administratör om problemet kvarstår.", "Vaktplanen kunne ikke lastes. Last siden på nytt, eller kontakt en administrator hvis problemet fortsetter.")
a("Could not reach the server to search. Check your network and try again.", "Serveren kunne ikke nås til søgning. Kontrollér netværket, og prøv igen.", "Servern kunde inte nås för sökning. Kontrollera nätverket och försök igen.", "Serveren kunne ikke nås for søk. Kontroller nettverket, og prøv igjen.")

a("Duty assignments and absences stay on your Nextcloud. There is no vendor cloud copy of your roster.", "Vagttildelinger og fravær bliver på Nextcloud. Der findes ingen leverandør-cloudkopi af vagtplanen.", "Pass-tilldelningar och frånvaro stannar på Nextcloud. Det finns ingen leverantörsmolnkopia av schemat.", "Vakt­tildelinger og fravær blir på Nextcloud. Det finnes ingen leverandør-skykopi av vaktplanen.")
a("DutyCheck is unavailable until your Nextcloud account is linked to an active employee record.", "DutyCheck er utilgængeligt, indtil Nextcloud-kontoen er linket til en aktiv medarbejderpost.", "DutyCheck är otillgängligt tills Nextcloud-kontot är kopplat till en aktiv anställdpost.", "DutyCheck er utilgjengelig til Nextcloud-kontoen er koblet til en aktiv ansattpost.")
a("DutyCheck is unavailable until your Nextcloud account is linked to an employee record. Ask a planner or administrator.", "DutyCheck er utilgængeligt, indtil Nextcloud-kontoen er linket til en medarbejderpost. Kontakt en planlægger eller administrator.", "DutyCheck är otillgängligt tills Nextcloud-kontot är kopplat till en anställdpost. Kontakta en planerare eller administratör.", "DutyCheck er utilgjengelig til Nextcloud-kontoen er koblet til en ansattpost. Kontakt en planlegger eller administrator.")
a("DutyCheck still has {count} legacy absence record(s) for linked employees. Remove them below before enabling integration.", "DutyCheck har stadig {count} ældre fraværspost(er) for linkede medarbejdere. Fjern dem nedenfor, før integration aktiveres.", "DutyCheck har fortfarande {count} äldre frånvaropost(er) för länkade anställda. Ta bort dem nedan innan integration aktiveras.", "DutyCheck har fortsatt {count} eldre fraværspost(er) for tilknyttede ansatte. Fjern dem nedenfor før integrasjon aktiveres.")
a("Each location has its own timezone (not a global app setting). Defaults to your account timezone when you add a new location.", "Hver lokation har sin egen tidszone (ikke en global app-indstilling). Ved ny lokation bruges kontoens tidszone som standard.", "Varje plats har sin egen tidszon (inte en global appinställning). Vid ny plats används kontots tidszon som standard.", "Hvert sted har sin egen tidssone (ikke en global app-innstilling). Ved nytt sted brukes kontoens tidssone som standard.")
a("Every published shift assigned to you in the selected range. If anything looks wrong, contact your planner before the shift starts.", "Alle offentliggjorte vagter i det valgte interval. Kontakt planlæggeren før vagtstart, hvis noget ser forkert ud.", "Alla publicerade pass i det valda intervallet. Kontakta planeraren före passstart om något verkar fel.", "Alle publiserte vakter i det valgte intervallet. Kontakt planleggeren før vaktstart hvis noe ser feil ut.")
a("Everyone here is linked to a Nextcloud account — add or change their absences in ArbeitszeitCheck. The table below still shows what you need for the roster.", "Alle her er linket til en Nextcloud-konto — fravær tilføjes eller ændres i ArbeitszeitCheck. Tabellen nedenfor viser stadig det nødvendige til vagtplanen.", "Alla här är kopplade till ett Nextcloud-konto — frånvaro läggs till eller ändras i ArbeitszeitCheck. Tabellen nedan visar fortfarande det som behövs för schemat.", "Alle her er koblet til en Nextcloud-konto — fravær legges til eller endres i ArbeitszeitCheck. Tabellen nedenfor viser fortsatt det som trengs for vaktplanen.")
a('Everything you send stays "Pending" until reviewed. For a single day off, use the same date twice.', "Alt indsendt forbliver «Afventer», indtil det er gennemgået. For en enkelt fridag skal samme dato angives to gange.", "Allt som skickas in förblir «Väntar» tills det har granskats. För en enstaka ledig dag ska samma datum anges två gånger.", "Alt innsendt forblir «Venter» til det er vurdert. For én enkelt fridag skal samme dato oppgis to ganger.")
a("Filled automatically when you link an account; edit if needed.", "Udfyldes automatisk ved kontolink; rediger ved behov.", "Fylls i automatiskt vid kontokoppling; redigera vid behov.", "Fylles automatisk ved kontokobling; rediger ved behov.")
a("Finish the highlighted step — then your team can plan duties.", "Fuldfør det fremhævede trin — derefter kan teamet planlægge vagter.", "Slutför det markerade steget — därefter kan teamet planera pass.", "Fullfør det uthevede trinnet — deretter kan teamet planlegge vakter.")
a("Form cleared. You can enter another assignment.", "Formular ryddet. Der kan indtastes endnu en tildeling.", "Formuläret rensades. Ytterligare ett uppdrag kan anges.", "Skjema tømt. Det kan legges inn enda en tildeling.")
a("How to add a duty assignment without breaking labour rules or double-booking anyone.", "Sådan tilføjes en vagttildeling uden at bryde arbejdsregler eller dobbeltbooke nogen.", "Så lägger man till en pass­tilldelning utan att bryta arbetsregler eller dubbelboka någon.", "Slik legges en vakt­tildeling til uten å bryte arbeidsregler eller dobbeltbooke noen.")
a("If Save asks you to confirm, a planning rule was triggered (for example less than 11 hours rest between shifts). You can review issues in", "Hvis Gem beder om bekræftelse, blev en planlægningsregel udløst (f.eks. mindre end 11 timers hvile mellem vagter). Problemer kan gennemgås i", "Om Spara begär bekräftelse utlöstes en planeringsregel (t.ex. mindre än 11 timmars vila mellan pass). Problem kan granskas i", "Hvis Lagre ber om bekreftelse, ble en planleggingsregel utløst (f.eks. mindre enn 11 timers hvile mellom vakter). Problemer kan gjennomgås i")
a("If a request is rejected or cancelled, the planner adds a written reason next to the status — so you know what to do next.", "Hvis en anmodning afvises eller annulleres, tilføjer planlæggeren en skriftlig begrundelse ved status — så næste skridt er klart.", "Om en begäran avslås eller annulleras lägger planeraren till en skriftlig motivering vid status — så nästa steg är tydligt.", "Hvis en forespørsel avvises eller kanselleres, legger planleggeren til en skriftlig begrunnelse ved status — så neste steg er klart.")
a("If you believe this is a mistake, contact your DutyCheck administrator and ask to be granted a planner or employee role.", "Hvis dette anses for en fejl, kontakt DutyCheck-administrationen, og bed om rollen planlægger eller medarbejder.", "Om detta bedöms vara ett fel, kontakta DutyCheck-administrationen och begär rollen planerare eller anställd.", "Hvis dette anses som en feil, kontakt DutyCheck-administrasjonen, og be om rollen planlegger eller ansatt.")
a("If your organisation restricts DutyCheck, ask an administrator to add you to the allowed users or groups in Settings.", "Hvis organisationen begrænser DutyCheck, bed en administrator om at tilføje brugeren eller gruppen under Indstillinger.", "Om organisationen begränsar DutyCheck, be en administratör lägga till användaren eller gruppen under Inställningar.", "Hvis organisasjonen begrenser DutyCheck, be en administrator legge til brukeren eller gruppen under Innstillinger.")
a("Legacy DutyCheck absences exist on linked employees. Resolve them before enabling integration ({count} rows).", "Ældre DutyCheck-fravær findes for linkede medarbejdere. Løs dem, før integration aktiveres ({count} rækker).", "Äldre DutyCheck-frånvaro finns för länkade anställda. Lös dem innan integration aktiveras ({count} rader).", "Eldre DutyCheck-fravær finnes for tilknyttede ansatte. Løs dem før integrasjon aktiveres ({count} rader).")
a("Legacy DutyCheck absences exist on linked employees. Resolve them before enabling integration.", "Ældre DutyCheck-fravær findes for linkede medarbejdere. Løs dem, før integration aktiveres.", "Äldre DutyCheck-frånvaro finns för länkade anställda. Lös dem innan integration aktiveras.", "Eldre DutyCheck-fravær finnes for tilknyttede ansatte. Løs dem før integrasjon aktiveres.")
a("List prices on our site apply to published Check apps. For this app, ask for an individual partner offer — we invoice only after you accept a quote.", "Listepriser på vores side gælder for offentliggjorte Check-apps. For denne app skal der anmodes om et individuelt partnertilbud — fakturering sker først efter accept af tilbud.", "Listpriser på vår webbplats gäller publicerade Check-appar. För denna app ska ett individuellt partnererbjudande begäras — fakturering sker först efter accept av offert.", "Listepriser på nettstedet gjelder publiserte Check-apper. For denne appen må det be om et individuelt partnertilbud — fakturering skjer først etter aksept av tilbud.")
a("Network error. Please check your connection and retry.", "Netværksfejl. Kontrollér forbindelsen, og prøv igen.", "Nätverksfel. Kontrollera anslutningen och försök igen.", "Nettverksfeil. Kontroller tilkoblingen, og prøv igjen.")
a("New to DutyCheck? Three short steps to get a roster ready for your team.", "Ny i DutyCheck? Tre korte trin for at gøre en vagtplan klar til teamet.", "Ny på DutyCheck? Tre korta steg för att göra ett schema klart för teamet.", "Ny i DutyCheck? Tre korte trinn for å gjøre en vaktplan klar for teamet.")
a("Newest first. Statuses update after your planner reviews each row.", "Nyeste først. Status opdateres, når planlæggeren har gennemgået hver række.", "Nyaste först. Status uppdateras när planeraren har granskat varje rad.", "Nyeste først. Status oppdateres når planleggeren har vurdert hver rad.")
a("No absences shown here yet. Request time off in ArbeitszeitCheck — approved leave will appear for your planner after the next sync.", "Ingen fravær vist endnu. Anmod om fri i ArbeitszeitCheck — godkendt fravær vises for planlæggeren efter næste synkronisering.", "Ingen frånvaro visas ännu. Begär ledighet i ArbeitszeitCheck — godkänd frånvaro visas för planeraren efter nästa synkronisering.", "Ingen fravær vist ennå. Be om fri i ArbeitszeitCheck — godkjent fravær vises for planleggeren etter neste synkronisering.")
a("No matches found. Keep typing to refine your search.", "Ingen resultater. Fortsæt indtastningen for at indsnævre søgningen.", "Inga träffar. Fortsätt skriva för att förfina sökningen.", "Ingen treff. Fortsett å skrive for å avgrense søket.")
a("Note for your planner (optional)", "Note til planlægger (valgfrit)", "Anteckning till planerare (valfritt)", "Merknad til planlegger (valgfritt)")
a("On the Roster page, use “Add assignment” for each shift. “Must fix” issues (e.g. someone in two places at once) block saving. “Confirm to continue” items need a short written reason. Then publish the period so employees can see their roster.", "På vagtplansiden bruges «Tilføj tildeling» for hver vagt. «Skal rettes»-problemer (f.eks. samme person to steder) blokerer gemning. «Bekræft for at fortsætte» kræver kort skriftlig begrundelse. Offentliggør derefter perioden, så medarbejdere kan se vagtplanen.", "På schemasidan används «Lägg till uppdrag» för varje pass. «Måste åtgärdas»-problem (t.ex. samma person på två ställen) blockerar sparning. «Bekräfta för att fortsätta» kräver kort skriftlig motivering. Publicera sedan perioden så att personal kan se schemat.", "På vaktplansiden brukes «Legg til tildeling» for hver vakt. «Må rettes»-problemer (f.eks. samme person to steder) blokkerer lagring. «Bekreft for å fortsette» krever kort skriftlig begrunnelse. Publiser deretter perioden, så ansatte kan se vaktplanen.")
a("Open DutyCheck to see your shifts.", "Åbn DutyCheck for at se vagter.", "Öppna DutyCheck för att se pass.", "Åpne DutyCheck for å se vakter.")
a("Open DutyCheck to see your updated roster.", "Åbn DutyCheck for at se den opdaterede vagtplan.", "Öppna DutyCheck för att se det uppdaterade schemat.", "Åpne DutyCheck for å se den oppdaterte vaktplanen.")
a("Open Roster, use “Add assignment” for each shift, and resolve every “Must fix” issue before continuing.", "Åbn vagtplanen, brug «Tilføj tildeling» for hver vagt, og løs alle «Skal rettes»-problemer, før der fortsættes.", "Öppna schemat, använd «Lägg till uppdrag» för varje pass, och lös alla «Måste åtgärdas»-problem innan fortsättning.", "Åpne vaktplanen, bruk «Legg til tildeling» for hver vakt, og løs alle «Må rettes»-problemer før fortsettelse.")
a("Open your calendar app and choose something like “Subscribe”, “Add calendar”, or “From URL” (the name differs per app).", "Åbn kalenderappen, og vælg noget som «Abonner», «Tilføj kalender» eller «Fra URL» (navnet varierer pr. app).", "Öppna kalenderappen och välj något som «Prenumerera», «Lägg till kalender» eller «Från URL» (namnet varierar per app).", "Åpne kalenderappen, og velg noe som «Abonner», «Legg til kalender» eller «Fra URL» (navnet varierer per app).")
a("Paste the address. You usually only do this once; the app refreshes your shifts in the background.", "Indsæt adressen. Det gøres normalt kun én gang; appen opdaterer vagter i baggrunden.", "Klistra in adressen. Det görs normalt bara en gång; appen uppdaterar pass i bakgrunden.", "Lim inn adressen. Det gjøres normalt bare én gang; appen oppdaterer vakter i bakgrunnen.")
a("Paste the full key from your license email. Line breaks are OK.", "Indsæt den fulde nøgle fra license-mailen. Linjeskift er OK.", "Klistra in hela nyckeln från licensmejlet. Radbrytningar är OK.", "Lim inn hele nøkkelen fra lisens-e-posten. Linjeskift er OK.")
a("Period", "Tidsperiode", "Tidsperiod", "Tidsperiode")
a("Period totals and daily limits used by planning checks. Defaults stay ArbZG-oriented until you change them.", "Periodetotaler og daglige grænser brugt af planlægningskontroller. Standarder forbliver ArbZG-orienterede, indtil de ændres.", "Periodsummor och dagliga gränser som används av planeringskontroller. Standardvärden förblir ArbZG-orienterade tills de ändras.", "Periodetotaler og daglige grenser brukt av planleggingskontroller. Standardverdier forblir ArbZG-orienterte til de endres.")
a("Periods are listed newest first. Closed periods are read-only. Changing the period updates the list below — no full page reload.", "Perioder vises med nyeste først. Lukkede perioder er skrivebeskyttede. Skift af periode opdaterer listen nedenfor — uden fuld sidegenindlæsning.", "Perioder listas med nyaste först. Stängda perioder är skrivskyddade. Byte av period uppdaterar listan nedan — utan full siduppdatering.", "Perioder vises med nyeste først. Lukkede perioder er skrivebeskyttede. Endring av periode oppdaterer listen nedenfor — uten full sideoppdatering.")
a("Periods are the timeline of your roster. Each period flows through three stages: open, published, closed.", "Perioder er tidslinjen for vagtplanen. Hver periode går gennem tre faser: åben, offentliggjort, lukket.", "Perioder är tidslinjen för schemat. Varje period går igenom tre faser: öppen, publicerad, stängd.", "Perioder er tidslinjen for vaktplanen. Hver periode går gjennom tre faser: åpen, publisert, lukket.")
a("Pick a quick range or enter your own dates. Only published shifts are shown.", "Vælg et hurtigt interval, eller angiv egne datoer. Kun offentliggjorte vagter vises.", "Välj ett snabbintervall eller ange egna datum. Endast publicerade pass visas.", "Velg et hurtigintervall, eller angi egne datoer. Kun publiserte vakter vises.")
a("Pick a start and end date below to create your first planning period.", "Vælg start- og slutdato nedenfor for at oprette den første planlægningsperiode.", "Välj start- och slutdatum nedan för att skapa den första planeringsperioden.", "Velg start- og sluttdato nedenfor for å opprette den første planleggingsperioden.")
a("Pick a type, a start and end date, and submit. Earlier requests give your planner more flexibility to find cover.", "Vælg type, start- og slutdato, og indsend. Tidligere anmodninger giver planlæggeren mere fleksibilitet til at finde afløsning.", "Välj typ, start- och slutdatum, och skicka in. Tidigare begäranden ger planeraren mer flexibilitet att hitta vikarie.", "Velg type, start- og sluttdato, og send inn. Tidligere forespørsler gir planleggeren mer fleksibilitet til å finne vikar.")
a("Planning rule needs your confirmation", "Planlægningsregel kræver bekræftelse", "Planeringsregel kräver bekräftelse", "Planleggingsregel krever bekreftelse")
a("Pre-filled with {n} min — same as your last shift.", "Forudfyldt med {n} min — samme som sidste vagt.", "Förifyllt med {n} min — samma som senaste pass.", "Forhåndsutfylt med {n} min — samme som forrige vakt.")
a("Preview never writes. Apply only after you confirm the dry-run counts. Conflicts are recomputed after apply.", "Forhåndsvisning skriver aldrig. Anvend først efter bekræftelse af tørkørselstallet. Konflikter genberegnes efter anvendelse.", "Förhandsgranskning skriver aldrig. Verkställ först efter bekräftelse av testkörningssiffrorna. Konflikter beräknas om efter verkställning.", "Forhåndsvisning skriver aldrig. Bruk først etter bekreftelse av testkjøringstallene. Konflikter beregnes på nytt etter bruk.")
a("Remote onboarding or a workshop so your team can roll out cleanly — billed as a service.", "Fjernonboarding eller et workshop, så teamet kan rulle ud rent — faktureret som service.", "Fjärrintroduktion eller en workshop så att teamet kan rulla ut ordnat — faktureras som tjänst.", "Fjernonboarding eller et workshop, slik at teamet kan rulle ut ryddig — faktureres som tjeneste.")
a("Remove this license?", "Fjerne denne licens?", "Ta bort denna licens?", "Fjerne denne lisensen?")
a("Create calendar link?", "Oprette kalenderlink?", "Skapa kalenderlänk?", "Opprette kalenderlenke?")
a("Deactivate location?", "Deaktivere lokation?", "Inaktivera plats?", "Deaktivere sted?")
a("Replace calendar link?", "Erstatte kalenderlink?", "Byta kalenderlänk?", "Erstatte kalenderlenke?")
a("Request time off in ArbeitszeitCheck. DutyCheck only lists it here for your planner.", "Anmod om fri i ArbeitszeitCheck. DutyCheck viser det kun her til planlæggeren.", "Begär ledighet i ArbeitszeitCheck. DutyCheck visar det bara här för planeraren.", "Be om fri i ArbeitszeitCheck. DutyCheck viser det bare her for planleggeren.")
a("Resolve every “Must fix” issue before continuing.", "Løs alle «Skal rettes»-problemer, før der fortsættes.", "Lös alla «Måste åtgärdas»-problem innan fortsättning.", "Løs alle «Må rettes»-problemer før fortsettelse.")
a("See your requests first, then send a new one if you need time off.", "Gennemse anmodninger først, og send en ny, hvis der er behov for fri.", "Granska begäranden först och skicka en ny om ledighet behövs.", "Se gjennom forespørsler først, og send en ny hvis fri trengs.")
a("Select a period before adding assignments.", "Vælg en periode, før tildelinger tilføjes.", "Välj en period innan uppdrag läggs till.", "Velg en periode før tildelinger legges til.")
a("Select a period before saving.", "Vælg en periode, før der gemmes.", "Välj en period innan sparning.", "Velg en periode før lagring.")
a("Select a period to load its lifecycle, snapshots, and audit trail. You can publish only when every “Must fix” issue is resolved and “Confirm to continue” items are confirmed.", "Vælg en periode for at indlæse livscyklus, snapshots og revisionsspor. Offentliggørelse er mulig, når alle «Skal rettes»-problemer er løst, og «Bekræft for at fortsætte»-punkter er bekræftet.", "Välj en period för att ladda livscykel, ögonblicksbilder och granskningslogg. Publicering är möjlig när alla «Måste åtgärdas»-problem är lösta och «Bekräfta för att fortsätta»-punkter är bekräftade.", "Velg en periode for å laste livssyklus, øyeblikksbilder og revisjonsspor. Publisering er mulig når alle «Må rettes»-problemer er løst, og «Bekreft for å fortsette»-punkter er bekreftet.")
a("Setup is required before you can plan duties.", "Opsætning er påkrævet, før vagter kan planlægges.", "Konfiguration krävs innan pass kan planeras.", "Oppsett er påkrevd før vakter kan planlegges.")
a("Shift times use the location timezone ({locationTimezone}). Change it on the Locations page. Your account timezone ({accountTimezone}) is shown in the header.", "Vagttider bruger lokationens tidszone ({locationTimezone}). Ændres på siden Lokationer. Kontoens tidszone ({accountTimezone}) vises i sidehovedet.", "Passtider använder platsens tidszon ({locationTimezone}). Ändras på sidan Platser. Kontots tidszon ({accountTimezone}) visas i sidhuvudet.", "Vakttider bruker stedets tidssone ({locationTimezone}). Endres på siden Steder. Kontoens tidssone ({accountTimezone}) vises i toppteksten.")
a("Some items still need your confirmation.", "Nogle punkter kræver stadig bekræftelse.", "Vissa punkter kräver fortfarande bekräftelse.", "Noen punkter krever fortsatt bekreftelse.")
a("Start", "Begynd", "Start", "Begynn")
a("Templates fill start, end, and break. You can still change any field before saving.", "Skabeloner udfylder start, slut og pause. Ethvert felt kan stadig ændres før gemning.", "Mallar fyller start, slut och rast. Vilket fält som helst kan fortfarande ändras före sparning.", "Maler fyller start, slutt og pause. Ethvert felt kan fortsatt endres før lagring.")
a("The DutyCheck web app always stays free. A DTY2 license unlocks named seats for the official DutyCheck mobile companion app for your organisation.", "DutyCheck-webappen forbliver altid gratis. En DTY2-licens låser op for navngivne pladser til den officielle DutyCheck-mobilapp for organisationen.", "DutyCheck-webbappen förblir alltid gratis. En DTY2-licens låser upp namngivna platser för den officiella DutyCheck-mobilappen för organisationen.", "DutyCheck-webappen forblir alltid gratis. En DTY2-lisens låser opp navngitte plasser til den offisielle DutyCheck-mobilappen for organisasjonen.")
a("The address is hidden here. Use “Replace calendar link” to create a fresh address you can copy.", "Adressen er skjult her. Brug «Erstat kalenderlink» for at oprette en ny adresse, der kan kopieres.", "Adressen är dold här. Använd «Byt kalenderlänk» för att skapa en ny adress som kan kopieras.", "Adressen er skjult her. Bruk «Erstatt kalenderlenke» for å opprette en ny adresse som kan kopieres.")
a("This Roster page stores shifts only. Publishing and closing happen on Periods — employees see My roster only after you publish there. Publish only when every “Must fix” issue is resolved and “Confirm to continue” items are confirmed.", "Denne vagtplanside gemmer kun vagter. Offentliggørelse og lukning sker under Perioder — medarbejdere ser Min vagtplan først efter offentliggørelse der. Offentliggør først, når alle «Skal rettes»-problemer er løst, og «Bekræft for at fortsætte»-punkter er bekræftet.", "Denna schemasida lagrar bara pass. Publicering och stängning sker under Perioder — personal ser Mitt schema först efter publicering där. Publicera först när alla «Måste åtgärdas»-problem är lösta och «Bekräfta för att fortsätta»-punkter är bekräftade.", "Denne vaktplansiden lagrer bare vakter. Publisering og lukking skjer under Perioder — ansatte ser Min vaktplan først etter publisering der. Publiser først når alle «Må rettes»-problemer er løst, og «Bekreft for å fortsette»-punkter er bekreftet.")
a("This creates a secret web address for your calendar app. Anyone with the address can see your published shifts. Only continue if this device is private to you.", "Dette opretter en hemmelig webadresse til kalenderappen. Alle med adressen kan se offentliggjorte vagter. Fortsæt kun, hvis enheden er privat.", "Detta skapar en hemlig webbadress till kalenderappen. Alla med adressen kan se publicerade pass. Fortsätt bara om enheten är privat.", "Dette oppretter en hemmelig nettadresse til kalenderappen. Alle med adressen kan se publiserte vakter. Fortsett bare hvis enheten er privat.")
a("This license expires in {days} day(s). Renew soon to avoid an interruption for your mobile seats.", "Denne licens udløber om {days} dag(e). Forny snart for at undgå afbrydelse af mobilsæder.", "Denna licens löper ut om {days} dag(ar). Förnya snart för att undvika avbrott för mobilplatser.", "Denne lisensen utløper om {days} dag(er). Forny snart for å unngå avbrudd for mobilplasser.")
a("This seat exceeds the current license limit. It stays assigned but has no mobile access until you remove a seat or upgrade.", "Denne plads overskrider den aktuelle licensgrænse. Den forbliver tildelt, men har ingen mobiladgang, før en plads fjernes eller der opgraderes.", "Denna plats överskrider den aktuella licensgränsen. Den förblir tilldelad men har ingen mobilåtkomst tills en plats tas bort eller uppgradering sker.", "Denne plassen overskrider gjeldende lisensgrense. Den forblir tildelt, men har ingen mobiltilgang til en plass fjernes eller det oppgraderes.")
a("Tip: turn this on after you have already added at least one allowed user or group below, otherwise the app locks itself.", "Tip: aktiver dette, når mindst én tilladt bruger eller gruppe allerede er tilføjet nedenfor — ellers låser appen sig selv.", "Tips: aktivera detta när minst en tillåten användare eller grupp redan har lagts till nedan — annars låser appen sig själv.", "Tips: aktiver dette når minst én tillatt bruker eller gruppe allerede er lagt til nedenfor — ellers låser appen seg selv.")
a("Type", "Art", "Typ", "Art")
a("Unassigned shifts you can claim. Hard planning rules still apply — if a claim fails, ask your planner.", "Utildelte vagter kan overtages. Hårde planlægningsregler gælder stadig — hvis en anmodning mislykkes, kontakt planlæggeren.", "Otilldelade pass kan tas över. Hårda planeringsregler gäller fortfarande — om en begäran misslyckas, kontakta planeraren.", "Utildelte vakter kan overtas. Harde planleggingsregler gjelder fortsatt — hvis en forespørsel mislykkes, kontakt planleggeren.")
a("Walk through this list each time you prepare a period for publication.", "Gennemgå denne liste, hver gang en periode forberedes til offentliggørelse.", "Gå igenom denna lista varje gång en period förbereds för publicering.", "Gå gjennom denne listen hver gang en periode forberedes til publisering.")
a("Why are you turning the connection off? (optional)", "Hvorfor slås forbindelsen fra? (valgfrit)", "Varför stängs anslutningen av? (valfritt)", "Hvorfor slås tilkoblingen av? (valgfritt)")
a("You already have an overlapping absence.", "Der findes allerede et overlappende fravær.", "Det finns redan en överlappande frånvaro.", "Det finnes allerede et overlappende fravær.")
a("You already have the employee role, but no row in the Employees catalog references your user yet. Ask a planner or DutyCheck administrator to link your account there.", "Medarbejderrollen er allerede tildelt, men ingen række i medarbejderkataloget henviser endnu til brugeren. Bed en planlægger eller DutyCheck-administrator om at linke kontoen.", "Anställdrollen är redan tilldelad, men ingen rad i anställdkatalogen refererar ännu till användaren. Be en planerare eller DutyCheck-administratör koppla kontot.", "Ansattrollen er allerede tildelt, men ingen rad i ansattkatalogen refererer ennå til brukeren. Be en planlegger eller DutyCheck-administrator koble kontoen.")
a("You are currently not allowed to use DutyCheck based on directory restrictions.", "DutyCheck må ikke bruges i øjeblikket på grund af katalogbegrænsninger.", "DutyCheck får inte användas för närvarande på grund av katalogbegränsningar.", "DutyCheck kan ikke brukes for øyeblikket på grunn av katalogbegrensninger.")
a("You are currently not linked to DutyCheck. Ask an administrator to assign your role.", "Kontoen er ikke linket til DutyCheck i øjeblikket. Bed en administrator om at tildele rollen.", "Kontot är inte kopplat till DutyCheck för närvarande. Be en administratör tilldela rollen.", "Kontoen er ikke koblet til DutyCheck for øyeblikket. Be en administrator tildele rollen.")
a("You are not allowed to search the directory.", "Kataloget må ikke gennemsøges.", "Katalogen får inte sökas.", "Katalogen kan ikke søkes i.")
a("You are not allowed to use DutyCheck right now.", "DutyCheck må ikke bruges lige nu.", "DutyCheck får inte användas just nu.", "DutyCheck kan ikke brukes akkurat nå.")
a("You are not authorized to perform that action.", "Der er ikke autorisation til denne handling.", "Det finns ingen behörighet för denna åtgärd.", "Det finnes ikke autorisasjon for denne handlingen.")
a("You are scheduled for %1$s minutes this period (soft cap %2$s). Talk to your planner if this looks wrong.", "Der er planlagt %1$s minutter i denne periode (blød grænse %2$s). Kontakt planlæggeren, hvis det ser forkert ud.", "Det är planerat %1$s minuter denna period (mjuk gräns %2$s). Kontakta planeraren om det verkar fel.", "Det er planlagt %1$s minutter i denne perioden (myk grense %2$s). Kontakt planleggeren hvis det ser feil ut.")
a("You can still plan shifts here. To add or change time off, open ArbeitszeitCheck.", "Vagter kan stadig planlægges her. For at tilføje eller ændre fravær skal ArbeitszeitCheck åbnes.", "Pass kan fortfarande planeras här. För att lägga till eller ändra frånvaro, öppna ArbeitszeitCheck.", "Vakter kan fortsatt planlegges her. For å legge til eller endre fravær, åpne ArbeitszeitCheck.")
a("You can still see your roster in DutyCheck. To request or change time off, use ArbeitszeitCheck.", "Vagtplanen kan stadig ses i DutyCheck. For at anmode om eller ændre fravær skal ArbeitszeitCheck bruges.", "Schemat kan fortfarande ses i DutyCheck. För att begära eller ändra frånvaro, använd ArbeitszeitCheck.", "Vaktplanen kan fortsatt sees i DutyCheck. For å be om eller endre fravær, bruk ArbeitszeitCheck.")
a("You cannot add assignments for this period.", "Der kan ikke tilføjes tildelinger for denne periode.", "Uppdrag kan inte läggas till för denna period.", "Det kan ikke legges til tildelinger for denne perioden.")
a("You cannot create DutyCheck absences for this employee: linked accounts use ArbeitszeitCheck while the integration is on.", "Der kan ikke oprettes DutyCheck-fravær for denne medarbejder: linkede konti bruger ArbeitszeitCheck, mens integrationen er aktiv.", "DutyCheck-frånvaro kan inte skapas för denna anställd: länkade konton använder ArbeitszeitCheck medan integrationen är aktiv.", "DutyCheck-fravær kan ikke opprettes for denne ansatte: tilknyttede kontoer bruker ArbeitszeitCheck mens integrasjonen er aktiv.")
a("You changed the suggested break for this shift.", "Den foreslåede pause for denne vagt blev ændret.", "Den föreslagna rasten för detta pass ändrades.", "Den foreslåtte pausen for dette skiftet ble endret.")
a("You do not have access to this DutyCheck area. Use the navigation to return to a page that matches your role, or ask an administrator if you need a different role.", "Der er ikke adgang til dette DutyCheck-område. Brug navigationen for at vende tilbage til en side, der matcher rollen, eller bed om en anden rolle hos en administrator.", "Det finns ingen åtkomst till detta DutyCheck-område. Använd navigeringen för att återgå till en sida som matchar rollen, eller be om en annan roll hos en administratör.", "Det finnes ikke tilgang til dette DutyCheck-området. Bruk navigasjonen for å gå tilbake til en side som matcher rollen, eller be om en annen rolle hos en administrator.")
a("You do not have permission for this DutyCheck action. Open a section that matches your role, or ask an administrator.", "Der mangler tilladelse til denne DutyCheck-handling. Åbn et afsnit, der matcher rollen, eller kontakt en administrator.", "Behörighet saknas för denna DutyCheck-åtgärd. Öppna ett avsnitt som matchar rollen, eller kontakta en administratör.", "Tillatelse mangler for denne DutyCheck-handlingen. Åpne et avsnitt som matcher rollen, eller kontakt en administrator.")
a("You do not have permission for this action.", "Der mangler tilladelse til denne handling.", "Behörighet saknas för denna åtgärd.", "Tillatelse mangler for denne handlingen.")
a("You do not have permission to manage the DutyCheck license.", "Der mangler tilladelse til at administrere DutyCheck-licensen.", "Behörighet saknas för att hantera DutyCheck-licensen.", "Tillatelse mangler for å administrere DutyCheck-lisensen.")
a("You do not have permission to view or change app policy. Ask an app administrator if you need adjustments.", "Der mangler tilladelse til at se eller ændre app-politik. Kontakt en app-administrator ved behov for justeringer.", "Behörighet saknas för att visa eller ändra appolicy. Kontakta en appadministratör vid behov av justeringar.", "Tillatelse mangler for å se eller endre app-policy. Kontakt en app-administrator ved behov for justeringer.")
a("You have confirmed this shift", "Denne vagt er bekræftet", "Detta pass har bekräftats", "Dette skiftet er bekreftet")
a("You stay a member of Default so existing rosters remain visible.", "Medlemskab af Default bevares, så eksisterende vagtplaner forbliver synlige.", "Medlemskap i Default behålls så att befintliga scheman förblir synliga.", "Medlemskap i Default beholdes, slik at eksisterende vaktplaner forblir synlige.")
a("Your absence requests and statuses", "Fraværsanmodninger og statusser", "Frånvarobegäranden och statusar", "Fraværsforespørsler og statuser")
a("Your account is not linked to an employee record. Ask a planner to link your Nextcloud account before you can manage absences.", "Kontoen er ikke linket til en medarbejderpost. Bed en planlægger om at linke Nextcloud-kontoen, før fravær kan administreres.", "Kontot är inte kopplat till en anställdpost. Be en planerare koppla Nextcloud-kontot innan frånvaro kan hanteras.", "Kontoen er ikke koblet til en ansattpost. Be en planlegger koble Nextcloud-kontoen før fravær kan administreres.")
a("Your account is not linked to an employee record. Ask a planner to link your Nextcloud account before you can see duties or calendar links.", "Kontoen er ikke linket til en medarbejderpost. Bed en planlægger om at linke Nextcloud-kontoen, før vagter eller kalenderlinks kan ses.", "Kontot är inte kopplat till en anställdpost. Be en planerare koppla Nextcloud-kontot innan pass eller kalenderlänkar kan ses.", "Kontoen er ikke koblet til en ansattpost. Be en planlegger koble Nextcloud-kontoen før vakter eller kalenderlenker kan sees.")
a("Your account is not linked to an employee. Ask a planner to set this up.", "Kontoen er ikke linket til en medarbejder. Bed en planlægger om at konfigurere det.", "Kontot är inte kopplat till en anställd. Be en planerare konfigurera det.", "Kontoen er ikke koblet til en ansatt. Be en planlegger sette det opp.")
a("Your choice here controls the assignment list and planning checks below. Only open periods accept new assignments.", "Valget her styrer tildelingslisten og planlægningskontrollerne nedenfor. Kun åbne perioder accepterer nye tildelinger.", "Valet här styr uppdragslistan och planeringskontrollerna nedan. Endast öppna perioder accepterar nya uppdrag.", "Valget her styrer tildelingslisten og planleggingskontrollene nedenfor. Kun åpne perioder aksepterer nye tildelinger.")
a("Your license is about to expire", "Licensen udløber snart", "Licensen löper snart ut", "Lisensen utløper snart")
a("Your link appears here after you create it.", "Linket vises her, når det er oprettet.", "Länken visas här när den har skapats.", "Lenken vises her når den er opprettet.")
a("Your new link is ready. Copy it now and paste it into your calendar app. It will be hidden again after you leave this page.", "Det nye link er klar. Kopiér det nu, og indsæt det i kalenderappen. Det skjules igen ved forladelse af siden.", "Den nya länken är klar. Kopiera den nu och klistra in den i kalenderappen. Den döljs igen när sidan lämnas.", "Den nye lenken er klar. Kopier den nå, og lim den inn i kalenderappen. Den skjules igjen når siden forlates.")
a("Your old address stops working right away. Paste the new one into your calendar app so it keeps updating.", "Den gamle adresse stopper med det samme. Indsæt den nye i kalenderappen, så opdateringer fortsætter.", "Den gamla adressen slutar fungera direkt. Klistra in den nya i kalenderappen så att uppdateringar fortsätter.", "Den gamle adressen slutter å virke med en gang. Lim inn den nye i kalenderappen, slik at oppdateringer fortsetter.")
a("Your private link", "Privat link", "Privat länk", "Privat lenke")
a("Your published shifts in the selected range", "Offentliggjorte vagter i det valgte interval", "Publicerade pass i det valda intervallet", "Publiserte vakter i det valgte intervallet")
a("Your requests and statuses", "Anmodninger og statusser", "Begäranden och statusar", "Forespørsler og statuser")
a("Your security token expired. Please reload the page and try again.", "Sikkerhedstokenet er udløbet. Genindlæs siden, og prøv igen.", "Säkerhetstoken har löpt ut. Ladda om sidan och försök igen.", "Sikkerhetstokenet er utløpt. Last siden på nytt, og prøv igjen.")
a("Your session expired. Please reload and sign in again.", "Sessionen er udløbet. Genindlæs siden, og log ind igen.", "Sessionen har löpt ut. Ladda om sidan och logga in igen.", "Økten er utløpt. Last siden på nytt, og logg inn igjen.")
a("Your shift changed", "Vagten blev ændret", "Passet ändrades", "Vakten ble endret")
a("Your shift was cancelled", "Vagten blev aflyst", "Passet avbokades", "Vakten ble avlyst")
a("Your swap request was approved. Check your roster.", "Bytteanmodningen blev godkendt. Gennemse vagtplanen.", "Bytesbegäran godkändes. Granska schemat.", "Bytteforespørselen ble godkjent. Se gjennom vaktplanen.")
a("Your swap request was rejected. Check with your planner.", "Bytteanmodningen blev afvist. Kontakt planlæggeren.", "Bytesbegäran avslogs. Kontakta planeraren.", "Bytteforespørselen ble avvist. Kontakt planleggeren.")
a("Your time off is managed in ArbeitszeitCheck.", "Fravær administreres i ArbeitszeitCheck.", "Frånvaro hanteras i ArbeitszeitCheck.", "Fravær administreres i ArbeitszeitCheck.")
a("Your time off is managed in ArbeitszeitCheck. This page shows it to your planner. To request time off, use ArbeitszeitCheck.", "Fravær administreres i ArbeitszeitCheck. Denne side viser det for planlæggeren. For at anmode om fravær skal ArbeitszeitCheck bruges.", "Frånvaro hanteras i ArbeitszeitCheck. Denna sida visar det för planeraren. För att begära frånvaro, använd ArbeitszeitCheck.", "Fravær administreres i ArbeitszeitCheck. Denne siden viser det for planleggeren. For å be om fravær, bruk ArbeitszeitCheck.")
a("Your upcoming published duties", "Kommende offentliggjorte vagter", "Kommande publicerade pass", "Kommende publiserte vakter")

if __name__ == "__main__":
    out = Path(__file__).parent / "formal_scandinavian_data.json"
    out.write_text(json.dumps(T, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(T)} keys to {out}")
